import 'package:shared_preferences/shared_preferences.dart';
import 'package:flutter/cupertino.dart';

class LanguageProvider extends ChangeNotifier {
  List<String> languageList = ['English', 'Arabic'];
  bool isEnglish = false;
  Map<String, String> arabicTexts = {
    "login": "تسجيل دخول",
    "mainPage": "الرئيسيه",
    "welcome": "مرحبا بك /",
    "setting": "الاعدادات",
    "contactUs": "تواصل معنا",
    "whoAreWe": "من نحن",
    "licenses": "التراخيص",
    "logOut": "الخروج",
    'language': "تغير الي الانجليزيه",
    "bills": "فواتير",
    "reports": "التقارير",
    "categories": "الأصناف",
    "sales": "مبيعات",
    "add": "أضافه",
    "bill": "فاتوره",
    "copy": "نسخ",
    "save": "حفظ",
    "registrationCode": "رمز التسجيل",
    "deviceSymbol": "رمز الجهاز",
    "write": "اكتب هنا",
    "send": "ارسال",
    "message": "الرساله",
    "mobile": "رقم الجوال",
    "name": "الاسم باكامل",
    "addClient": "إضافه عميل",
    "serialNumber": "رقم المسلسل",
    "account": "اسم الحساب",
    "cash": "نقدى",
    "taxNumber": "الرقم الضريبي",
    "adress": "العنوان",
    "adressDetails": " اكتب العنوان بالتفصيل",
    "code": "الكود",
    "getCode": "جلب الكود",
    "discount": "الخصم",
    "discountValue": "قيمه الخصم",
    "discountCoupon": "كوبون الخصم",
    "total": ": الإجمالى  ",
    "final": "الإجمالى",
    "sr": "ر.س",
    "unitPrice": "سعر الوحده",
    "quantity": "الكميه",
    "categoryNotes": "الملاحظات الصنف",
    "addBill": "أضف فاتورة",
    "date": "التاريخ",
    "clientName": "اسم العميل",
    "notes": "الملاحظات",
    "barCode": "الباركود",
    "billSummary": "ملخص الفاتوره",
    "afterDiscount": "بعد الخصم",
    "taxes": "الضرائب",
    "paidUp": "المدفوع",
    "rest": "الباقى",
    "finalOutput": "الناتج النهائي",
    "paymentWay": "طرق الدفع",
    "amount": "المبلغ",
    "tables": "الطاولات",
    "secondTurn": "دور تانى",
    "internal": "داخلى",
    "external": "خارجى",
    "clientSearch": "بحث العملاء",
    "barCodeSearch": "بحث الباركود",
    "done": "تم",
    "search": "البحث",
    "ascending": "تصاعدي",
    "descending": "تنازلى",
    "reviewBills": "مراجعه الفواتير",
    "doneCopy": "تم النسخ",
    "billNotes": "ملاحظات الفاتوره",
    "userNumber": "رقم المستخدم",
    "delete": "حذف",
    "edit": "تعديل",
    "print": "طباعه",
    "noReadPermission": "عفوا ليس لديك تصريح القراءه",
    "noDeletePermission": "عفوا ليس لديك تصريح المسح",
    "noEditPermission": "عفوا ليس لديك تصريح التعديل",
    "noChangePricePermission": "عفوا ليس لديك تصريح تعديل السعر",
    "noReadReportPermission": "عفوا ليس لديك تصريح قراءه التقارير",
    "changeServerLink": "تغير عنوان الخادم",
    "ourGuest": "ضيفنا",
    "addServerLink": "أضف عنوان الخادم",
    "serverLink": "عنوان الخادم",
    "licensesPage": "صفحه التراخيص",
    "serverPage": "صفحه عنوان الخادم",
    "choose a branch": "اختر فرع",
    "choose a delegate": "اختر مندوب",
    "choose a user": "اختر مستخدم",
    "billing type": "نوع الفواتير",
    "from": "من",
    "to": "الي",
    "branch": "الفرع",
    "customer / supplier": "عميل / مورد",
    "the user": "المستخدم",
    "delegate": "مندوب",
    "editBill": "تعديل الفاتوره رقم",
    "ِarabic": "العربيه",
    "english": "English",
    "enterBillNotes": "ادخل ملاحظاتك علي المنتج",
    "searchWithName": "الاسم",
    "type": "النوع",
    "totalDiscount": "اجمالي الخصم",
    "visa": "فيزا",
    "result": "النتيجه",
    "maxDiscount": "عفوا الحد الأقصى للخصم",
    "cantDivideByZero": "عفوا ليس لديك سعر للمنتج",
    "categoriesSearch": "بحث الاصناف",
    "barCodeError": "لقد ادخلت الباركود خطأ",
    "wrongQuantity": "لقد ادخلت كميه خطأ",
    "couponDone": "تم تفعيل الكوبون",
    "couponWrong2": "لقد تخطيت الحد الاقصى لمرات استخدام الكوبون",
    "couponWrong3": "لقد تخطيت الحد الاقصى للاصناف المتاحه بهذا الكوبون",
    "couponWrong4": " لقدانتهت صلاحيه استخدام هذا الكوبون",
    "couponWrong5": "لا يوجد كوبون",
    "coupon": "كوبون الخصم",
    "thereIsNoBill": "لا يوجد فواتير لديك في",
    "pleaseAdd": " من فضلك اضف منتج",
    "completeYourData": "من فضلك اكمل بياناتك",
    "confirmYourData": "من فضلك ادخل رقم الهاتف واسم العميل",
    "completeMobileData": "من فضلك ادخل رقم الهاتف",
    "completeAccountData": "من فضلك ادخل اسم العميل",
    "confirmDelete": "هل تريد مسح هذه الفاتوره ؟ ",
    'yes': "نعم",
    'password': "كلمه المرور",
    'no': "لا",
    "addBillOk": "تم اضافه الفاتوره بنجاح",
    "addError": "خطا في اضافه الفاتوره ",
    "editBillOk": "تم تعديل الفاتوره بنجاح",
    "editError": "خطا في تعديل الفاتوره ",
    "printError": "لقد تخطيت الحد الاقصي للطباعه",
    "cancelCoupon": "الغاء الكوبون",
    "cancelLicence": "الغاء التراخيص",
    "noReport": "لا توجد تقارير لهذه الفترة",
    "errorDelete": "خطا في مسح الفاتوره",
    "billCode": "كود الصنف",
    "emailOrPhone": "البريد الاليكترونى او رقم الجوال",
    "thePriceIncludesTax": "السعر شامل الضريبه",
    "transfers": "مناقلات",
    "stock": "مخزون",
    "stocks": "المخزون",
    "basicCards": "البطاقات الاساسيه",
    "materialCard": "بطاقه المواد",
    "addMaterialCard": "اضافه بطاقه مواد",
    "addClientsCard": "اضافه بطاقه عملاء",
    "editMaterialCard": "تعديل بطاقه مواد",
    "unitsCard": "بطاقه الوحدات",
    "materialGroups": "مجموعات المواد",
    "inventoryCards": "بطاقه المستودعات",
    "barcodePrinting": "طباعه الباركود",
    "balanceCard": "بطاقه الموازين", //ننن
    "addBalanceCard": "اضافه بطاقه موازين", //ننن
    "balanceName": "اسم الميزان",
    "unitSizeWeight": "مقاس كود الوزن",
    "unitSizeWeightFractions": "مقاس كود الوزن-الكسور",
    "ReplaceQuantityWithPrice": "استبدال الكميه بالسعر",
    "balanceCode": "كود الميزان",
    "unitSize": "مقاس كود الصنف",
    "types": "الانواع",
    "typesMenu": "قائمه الانواع",
    "addType": "اضافه نوع",
    "noTypes": "لا يوجد انواع",
    "clientsCards": "بطاقه العملاء",
    "supplierCards": "بطاقه الموردون",
    "mainClassification": "التصنيف الرئيسى",
    "subcategories": "التصنيفات الفرعيه",
    "halls": "الصالات",
    "hallsMenu": "قائمه الصالات",
    "tablesHalls": "الطاولات داخل الصالات",
    "unit": "الوحده",
    "addUnit": "اضافه وحده",
    "noUnits": "لا يوجد وحدات",
    "noHalls": "لا يوجد صالات",
    "deleteUnits": "هل تريد حذف هذه الوحده ؟",
    "deleteTypes": "هل تريد حذف هذه النوع ؟",
    "product": "الصنف",
    "general": "عام",
    "units": "الوحدات",
    "attachedMaterial": "المواد المرفقه",
    "extraInformation": "معلومات اضافيه",
    "productMenu": "قائمه الأصناف",
    "unitMenu": "قائمه الوحدات",
    "groupMenu": "قائمه المجموعات",
    "addGroupMenu": "اضافه مجموعه مواد",
    "addProduct": "أضف صنف",
    "serial": "مسلسل",
    "purchasingPrice": "سعر الشراء",
    "sellingPrice": "سعر البيع",
    "tax": "الضريبه",
    "taxPercentage": "نسبه الضريبه",
    "productName": "اسم الصنف",
    "productNameEN": "اسم الصنف انجليزى",
    "productNameAR": "اسم الصنف عربي",
    "mainProduct": "الصنف الرئيسي",
    "accounts": "الحسابات",
    "productCode": "كود الصنف",
    "printersGroup": "مجموعة الطابعات",
    "mainOrNotebook": "رئيسي / دفتر",
    "categoryOrService": "الصنف / الخدمة",
    "productDescription": "وصف الصنف",
    "purchasePrice": "سعر الشراء",
    "sellPrice": "سعر البيع",
    "minimumOrder": "الحد الادني للطلب",
    "discountPercentage": "نسبه الخصم",
    "productImagePath": "مسار صوره الصنف",
    "category": "الفئه",
    "classification": "التصنيف",
    "supplier": "مورد",
    "expiryDate": "يخضع لنظام تاريخ الصلاحيه او اللوت",
    "unitSellPrice": "سعر البيع للوحدة الأساسية",
    "unitPurchasingPrice": "سعر الشراء للوحدة الأساسية",
    "sellPriceSoldUnit": "سعر البيع للوحده المباعة",
    "purchasePriceSoldUnit": "سعر الشراء للوحده المباعة",
    "addOrEdit": "اضافه/ تعديل",
    "addBarcodeForBill": "اضافه باركود للصنف",
    "addUnits": "اضافه وحده",
    "addHall": "اضافه صاله",
    "addBarcode": "اضافه باركود",
    "addExtraMaterial": "اضافه مواد مرفقه",
    "arrange": "الترتيب",
    "hide": "اخفاء",
    "groupName": "اسم المجموعه",
    "mainItems": "قائمة الاصناف الرئيسية",
    "service": "خدمه",
    "noProductName": "من فضلك تاكد من وجود اسم الصنف وسعر البيع",
    "doneAddProduct": "تمت اضافه الصنف بنجاح",
    "noUnit": "لا يوجد لديك وحدات",
    "errorDeleteItem": "عفوا لم يتم المسح حدث خطأ",
    "doneDeleteItem": "تم مسح الصنف بنجاح",
    "confirmDeleteItem": "هل تريد مسح هذا الصنف",
    "noProduct": "لا يوجد لديك اصناف",
    "sameUnit": "لديك أكثر من وحدة بنفس الاسم لهذا الصنف ، يرجى حذفها",
    "sameAttachedMaterial": "لديك اكثر من ماده مرفقه بنفس الاسم لهذا الصنف يرجي حذفها",
    "noMoreProduct": "لقد تخطيت الحد الاقصي للاصناف",
    "noMoreUnit": "لقد تخطيت الحد الاقصي للوحدات",

  };
  Map<String, String> englishTexts = {
    "login": "Login",
    "mainPage": "Main Page",
    "welcome": " welcome /",
    "setting": "Setting",
    "contactUs": "Contact Us",
    "whoAreWe": "who are we",
    "licenses": "licenses",
    "logOut": "Log Out",
    'language': "Change to Arabic",
    "bills": "Bills",
    "reports": "Reports",
    "categories": "Categories",
    "sales": "Sales",
    "add": "Add",
    "bill": "Bill",
    "copy": "Copy",
    "save": "Save",
    "registrationCode": "Registration Code",
    "deviceSymbol": "Device Symbol",
    "write": "Write here",
    "send": "Send",
    "message": "Message",
    "mobile": "Mobile",
    "name": "Full name",
    "addClient": "Add Client",
    "serialNumber": "Serial Number",
    "account": "Account Name",
    "cash": "Cash",
    "taxNumber": "Tax Number",
    "adress": "Adress",
    "adressDetails": " Write the Adress in full detail",
    "code": "Code",
    "getCode": "Get Code",
    "discount": "Discount",
    "discountValue": "Discount Value",
    "discountCoupon": "Discount Coupon",
    "total": "Total : ",
    "final": "Total",
    "sr": "SR",
    "unitPrice": "unit Price",
    "quantity": "Quantity",
    "categoryNotes": "Category Notes",
    "addBill": "Add Bill",
    "date": "Date",
    "clientName": "Client name",
    "notes": "Notes",
    "barCode": "BarCode",
    "billSummary": "Bill Summary",
    "afterDiscount": "after Discount",
    "taxes": "Taxes",
    "paidUp": "Paid Up",
    "rest": "Rest",
    "finalOutput": "Final Output",
    "paymentWay": "Payment way",
    "amount": "amount",
    "tables": "Tables",
    "secondTurn": "Second Turn",
    "internal": "Internal",
    "external": "External",
    "clientSearch": "Customer search",
    "barCodeSearch": "Barcode search",
    "done": "Done",
    "search": "Search",
    "ascending": "ascending",
    "descending": "Descending",
    "reviewBills": "ٍReview Bills",
    "doneCopy": "Copy is Done",
    "billNotes": "Bill Notes",
    "userNumber": "User Number",
    "print": "Print",
    "delete": "Delete",
    "edit": "Edit",
    "noReadPermission": "Sorry, you do not have read permission",
    "noDeletePermission": "Sorry, you do not have delete permission",
    "noEditPermission": "Sorry, you do not have edit permission",
    "noChangePricePermission":
    "Sorry, you do not have permission to edit the price",
    "noReadReportPermission":
    "Sorry, you do not have permission to read the reports",
    "changeServerLink": "Change Server Link",
    "ourGuest": "Our Guest",
    "addServerLink": "addServerLink",
    "serverLink": "Server Link",
    "licensesPage": "Licenses Page",
    "serverPage": "Server Page",
    "choose a delegate": "Choose a delegate",
    "choose a user": "Choose a user",
    "choose a branch": "Choose a branch",
    "billing type": "Billing type",
    "branch": "Branch",
    "from": "From",
    "to": "To",
    "customer / supplier": "Customer / Supplier",
    "the user": "The user",
    "delegate": "Delegate",
    "editBill": "Edit Bill Number",
    "ِarabic": "العربيه",
    "english": "English",
    "enterBillNotes": "Enter your feedback on the product",
    "searchWithName": "name",
    "type": "Type",
    "totalDiscount": "total Discount",
    "visa": "visa",
    'result': 'result',
    'password': "Password",
    "maxDiscount": "Sorry the maximum discount is",
    "cantDivideByZero": "Sorry, you do not have a price for the product",
    "categoriesSearch": "Categories Search",
    "barCodeError": "You entered the wrong barcode",
    "wrongQuantity": "You entered the wrong Quantity",
    "couponDone": "Coupon  has been activated",
    "couponWrong2":
    "You have exceeded the maximum number of times to use the coupon",
    "couponWrong3":
    "You have exceeded the maximum number of items available for this coupon",
    "couponWrong4": "This coupon has been expired",
    "couponWrong5": "There is no coupon Found",
    "coupon": "Discount coupon",
    "thereIsNoBill": "You have no bills at",
    "pleaseAdd": "Please Add Product",
    "noReport": "There are no reports for this period",
    "completeYourData": "Please Complete Your Data",
    "confirmYourData": "Please enter the phone number and the customer's name",
    "completeMobileData": "Please enter the phone number",
    "completeAccountData": "Please enter the client name",
    "confirmDelete": "Do you want to clear this invoice ?",
    'yes': "Yes",
    'no': "No",
    "addBillOk": "Invoice added successfully",
    "addError": "Error adding invoice",
    "editBillOk": "Invoice Edit successfully",
    "editError": "Error Edit invoice",
    "printError": "Error You have exceeded the print limit",
    "cancelCoupon": "Cancel Coupon",
    "errorDelete": "Error in removing the bill",
    "billCode": "itemId",
    "cancelLicence": "Cancel Licences",
    "emailOrPhone": "Email or mobile number",
    "thePriceIncludesTax": "The Price Includes Tax",
    "transfers": "Transfers",
    "stock": "Stock",
    "stocks": "Stocks",
    "basicCards": "Basic Cards",
    "materialCard": "Material card",
    "addMaterialCard": "add Material Card",
    "addClientsCard": "add Clients Card",
    "editMaterialCard": "edit Material Card",
    "unitsCard": "Units Card",
    "materialGroups": "Material groups",
    "inventoryCards": "Inventory cards",
    "barcodePrinting": "Barcode printing",
    "balanceCard": "Balance Card",
    "addBalanceCard": "Add Balance Card",
    "balanceName": "Balance Name",
    "balanceCode": "Balance Code",
    "unitSize": "Item code size",
    "unitSizeWeight": "Weight code size",
    "unitSizeWeightFractions": "Weight code size Fractions",
    "ReplaceQuantityWithPrice": "replace Quantity With Price",
    "types": "Types",
    "typesMenu": "Types Menu",
    "addType": "add Type",
    "noTypes": "no Types",
    "clientsCards": "Clients Cards",
    "supplierCards": "Supplier Cards",
    "mainClassification": "The main classification",
    "subcategories": "Subcategories",
    "halls": "Halls",
    "hallsMenu": "Halls Menu",
    "tablesHalls": "Tables inside the halls",
    "unit": "Unit",
    "addUnit": "add Unit",
    "addHall": "add Hall",
    "noUnits": "There are no units",
    "noHalls": "There are no Halls",
    "deleteUnits": "Do you want to delete this unit?",
    "deleteTypes": "Do you want to delete this Type?",
    "product": "Product",
    "general": "General",
    "units": "units",
    "attachedMaterial": "Attached Material",
    "barcode": "Barcode",
    "extraInformation": "Extra Information",
    "productMenu": "Product Menu",
    "unitMenu": "‘Units Menu",
    "groupMenu": "‘Groups Menu",
    "addGroupMenu": "Add a set of items",
    "addProduct": "Add Product",
    "serial": "Serial",
    "sellingPrice": "Selling price",
    "purchasingPrice": "Purchasing price",
    "tax": "tax",
    "taxPercentage": "Tax Percentage",
    "productName": "Product Name",
    "productNameEN": "Product Name EN",
    "productNameAR": "Product Name Ar",
    "mainProduct": "Main Category",
    "accounts": "Accounts",
    "productCode": "Product Code",
    "printersGroup": "Printers group",
    "mainOrNotebook": "main / notebook",
    "categoryOrService": "Category / Service",
    "productDescription": "Product Description",
    "purchasePrice": "Purchasing Price",
    "discountPercentage": "Discount percentage",
    "minimumOrder": "Minimum Order",
    "sellPrice": "Selling Price",
    "productImagePath": "Product image path",
    "category": "Category",
    "classification": "Classification",
    "supplier": "Supplier",
    "expiryDate": "It is subject to the expiry date or lot system",
    "unitPurchasingPrice": "The purchase price of the base unit",
    "unitSellPrice": "The selling price is for the base unit",
    "purchasePriceSoldUnit": "Purchase price per sold unit",
    "sellPriceSoldUnit": "Selling price per unit sold",
    "addOrEdit": "add / Edit",
    "addBarcodeForBill": "Add a barcode to the Product",
    "addUnits": "Add Unit",
    "addBarcode": "Add Barcode",
    "addExtraMaterial": "Add Extra Material",
    "arrange": "Arrange",
    "hide": "Hide",
    "groupName": "Group Name",
    "mainItems": "Main items List",
    "service": "Service",
    "noProductName":
    "Please make sure that the name of the item and the selling price are present",
    "doneAddProduct": "The item has been added successfully",
    "noUnit": "There are no Other Units",
    "errorDeleteItem": "Sorry, the Delete was not completed. An error occurred",
    "doneDeleteItem": "The item has been Deleted successfully",
    "confirmDeleteItem": "Do you want to delete this item?",
    "noProduct": "You do not have items",
    "sameUnit": "You have more than one unit with the same name for this item, please delete it",
    "sameAttachedMaterial": "You have more than one item attached to this item with the same name, please delete it",
    "noMoreProduct": "You have exceeded the maximum items",
    "noMoreUnit": "You have exceeded the maximum number of units",
  };

  void changeLanguage({bool? englishLanguage}) async {
    final SharedPreferences sharedPrefernce =
    await SharedPreferences.getInstance();

    isEnglish = englishLanguage!;
    sharedPrefernce.setBool('savedLanguage', isEnglish);
    notifyListeners();
  }

// ignore: missing_return
  String getTexts(String text) {
    if (isEnglish == true) return englishTexts[text]!;
    return arabicTexts[text]!;
  }

  Future<bool> getLanguage() async {
    final SharedPreferences sharedPrefernce =
    await SharedPreferences.getInstance();

    isEnglish = sharedPrefernce.getBool('savedLanguage') ?? false;

    notifyListeners();
    return isEnglish;
  }
}
